name: bump-version
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Conventional Changelog Action
      id: changelog
      uses: isman-usoh/conventional-changelog-action
      with:
        github-token: ${{ secrets.PATNAME }}
        output-file: 'false'
        skip-on-empty: 'true'